name: Markdown to Notion
description: Load a Markdown file to a Notion page

inputs:
  delete_existing:
    description: Whether to delete the existing block
    required: false
    default: 'true'
  file:
    description: Path of the Markdown file to load
    required: true
  notion_id:
    description: ID of the page you want to append the file to
    required: true
  notion_token:
    description: Token to use with the Notion API
    required: true

outputs:
  block_id:
    description: The ID of the new block that has been appended

runs:
  using: node12
  main: dist/index.js
branding:
  icon: upload
  color: gray-dark
